# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo10' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo10
pod ‘AFNetworking’
pod ‘YYCache’

end
